Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -42,15 +42,16 @@ jobs:
         run: |
           APP_DIR="${{ github.workspace }}/applications_user/ble_spam"
           echo "🔍 Checking for application directory: $APP_DIR"
-          ls -ld "$APP_DIR" || echo "❌ Directory not found"
+          find ${{ github.workspace }} -type d -name "ble_spam" || echo "❌ Directory not found"
 
           if [ -d "$APP_DIR" ]; then
             echo "✅ ble_spam folder exists!"
             ls -R "$APP_DIR"
           else
             echo "❌ ERROR: applications_user/ble_spam folder is MISSING!"
-            exit 1
+          exit 1
           fi
+
 
       - name: Move App to Firmware Directory
         run: |
